//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 11 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `ic-home-tab1-selected`.
    var icHomeTab1Selected: RswiftResources.ImageResource { .init(name: "ic-home-tab1-selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab1_unchecked`.
    var ic_home_tab1_unchecked: RswiftResources.ImageResource { .init(name: "ic_home_tab1_unchecked", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab2_selected`.
    var ic_home_tab2_selected: RswiftResources.ImageResource { .init(name: "ic_home_tab2_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab2_unchecked`.
    var ic_home_tab2_unchecked: RswiftResources.ImageResource { .init(name: "ic_home_tab2_unchecked", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab3_selected`.
    var ic_home_tab3_selected: RswiftResources.ImageResource { .init(name: "ic_home_tab3_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab3_unchecked`.
    var ic_home_tab3_unchecked: RswiftResources.ImageResource { .init(name: "ic_home_tab3_unchecked", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab4_selected`.
    var ic_home_tab4_selected: RswiftResources.ImageResource { .init(name: "ic_home_tab4_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab4_unchecked`.
    var ic_home_tab4_unchecked: RswiftResources.ImageResource { .init(name: "ic_home_tab4_unchecked", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab5_selected`.
    var ic_home_tab5_selected: RswiftResources.ImageResource { .init(name: "ic_home_tab5_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_home_tab5_unchecked`.
    var ic_home_tab5_unchecked: RswiftResources.ImageResource { .init(name: "ic_home_tab5_unchecked", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logo`.
    var logo: RswiftResources.ImageResource { .init(name: "logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `HomeGoodsCell`.
    var homeGoodsCell: RswiftResources.NibReference<HomeGoodsCell> { .init(name: "HomeGoodsCell", bundle: bundle) }

    func validate() throws {
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "trash.circle.fill") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'trash.circle.fill' is used in nib 'HomeGoodsCell', but couldn't be loaded.") } }
    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "logo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'logo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ViewController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}